tasks:
  - init: bundle install
    dbsetup: bundle exec rake db:create db:migrate db:seed
  - console: rails console
  - db: psql -h localhost -d postgres
  # - cache: redis-server
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8443
