version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env.dev
    ports: 
      - "3000:3000"
    command: bundle exec rails s -b '0.0.0.0'
    links:
      - db

  worker:
    build: .
    env_file:
      - .env.dev
    command: bundle exec rake jobs:work
    links:
      - db

  db:
    image: postgres:11.12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=learn
      - POSTGRES_PASSWORD=learn
      - POSTGRES_DB=learn_development