version: "3.9"

services:
  learnawesome:
    # single container will run both the app and the background worker
    build: .
    env_file:
      - .env.dev
    ports: 
      - "8443:8443"
      - "3000:3000"
    depends_on:
      - "pg13dbhost"
    volumes:
      - .:/app

  pg13dbhost:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=learn
      - POSTGRES_PASSWORD=learn
      - POSTGRES_DB=learndb
      