version: "3.9"

services:
  learnawesome:
    # single container will run both the app and the background worker
    build: .
    env_file:
      - .env.dev
    ports: 
      - "8443:8443"
      - "3000:3000"
    networks:
      - dev-network
    volumes:
      - .:/app
  
networks:
  dev-network:
    external: true