services:
  learnawesome:
    build:
      context: /Users/nileshtr/learn
      dockerfile: /Users/nileshtr/learn/Dockerfile
    command:
    - infinity
    depends_on:
      pg13dbhost:
        condition: service_started
    entrypoint:
    - sleep
    environment:
      DATABASE_HOST: pg13dbhost
      DATABASE_NAME: learndb
      DATABASE_PASSWORD: learn
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: learn
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      RACK_ENV: development
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: enabled
      RAILS_SERVE_STATIC_FILES: enabled
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: learn-dazzling_cerf
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8443
      published: 8443
      protocol: tcp
    - mode: ingress
      target: 3000
      published: 3000
      protocol: tcp
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: /Users/nileshtr/learn
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-learn-dazzling_cerf-learnawesome
      target: /home/vscode
  pg13dbhost:
    environment:
      POSTGRES_DB: learndb
      POSTGRES_PASSWORD: learn
      POSTGRES_USER: learn
    image: postgres:13.3
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: learn-dazzling_cerf
    networks:
      default: null
networks:
  default:
    name: learn-dazzling_cerf_default
volumes:
  vsCodeServerVolume-learn-dazzling_cerf-learnawesome:
    name: vsCodeServerVolume-learn-dazzling_cerf-learnawesome
